# -*- coding: utf-8 -*-
"""Tiny Archify-compatible SVG emitter for the two diagrams in this repo.
Node = (id, kind, x, y, w, label, sublabel, tag, context); h fixed at NH.
Edge = (id, from, to, label, variant, points, d, (lx, ly) | None)
Frame = (kind, fid, label, x, y, w, h, cls, textcls, rx)
"""
SIGILS = {
 'cloud': '<path d="M4.3 12.5h7.3a2.4 2.4 0 0 0 .2-4.8 4 4 0 0 0-7.5-1.3A3.1 3.1 0 0 0 4.3 12.5Z"/>',
 'backend': '<path d="M6 3 3 8l3 5M10 3l3 5-3 5"/>',
 'database': '<ellipse cx="8" cy="4" rx="5" ry="2"/>\n            <path d="M3 4v8c0 1.1 2.2 2 5 2s5-.9 5-2V4M3 8c0 1.1 2.2 2 5 2s5-.9 5-2"/>',
 'external': '<rect x="2.5" y="5" width="8.5" height="8" rx="1.5"/>\n            <path d="M8 2.5h5.5V8M13.5 2.5 7.5 8.5"/>',
 'messagebus': '<rect x="2" y="6.5" width="12" height="3" rx="1.5"/>\n            <path d="M5 6.5V4M11 6.5V4M8 9.5V12"/>',
 'frontend': '<rect x="2" y="3" width="12" height="10" rx="2"/>\n            <path d="M2 6.5h12"/>\n            <circle cx="4.1" cy="4.8" r=".7" class="sigil-fill"/>\n            <circle cx="6.3" cy="4.8" r=".7" class="sigil-fill"/>',
 'security': '<path d="M8 2.5 3 4.5v3.5c0 3 2.2 5 5 5.5 2.8-.5 5-2.5 5-5.5V4.5Z"/>\n            <path d="m6 8 1.5 1.5L10.5 6.5"/>',
}
VARIANT = {
 "default":  ("a-default",  "1.5", "url(#arrowhead)",          "t-muted"),
 "emphasis": ("a-emphasis", "1.8", "url(#arrowhead-emphasis)", "t-backend"),
 "dashed":   ("a-dashed",   "1.5", "url(#arrowhead-dashed)",   "t-messagebus"),
}
NH = 80

def esc(s):
    return s.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')

def build(title, viewbox, nodes, edges, frames, desc="An architecture diagram generated by Archify."):
    out=[]; A=out.append
    A('      <svg viewBox="0 0 %d %d" role="img" lang="en" aria-labelledby="archify-diagram-title archify-diagram-description" data-preset="classic" data-quality-profile="showcase">' % viewbox)
    A('        <title id="archify-diagram-title">%s</title>' % esc(title))
    A('        <desc id="archify-diagram-description">%s</desc>' % esc(desc))
    A('''        <!-- Definitions -->
        <defs>
          <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-default" />
          </marker>
          <marker id="arrowhead-emphasis" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-emphasis" />
          </marker>
          <marker id="arrowhead-security" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-security" />
          </marker>
          <marker id="arrowhead-dashed" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-dashed" />
          </marker>
          <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
            <path d="M 40 0 L 0 0 0 40" class="c-grid" stroke-width="0.5"/>
          </pattern>
        </defs>

        <!-- Background Grid -->
        <rect width="100%" height="100%" fill="url(#grid)" />
''')
    A('        <!-- Boundaries (behind everything) -->')
    for kind, fid, label, x, y, w, h, cls, _t, rx in frames:
        A('        <rect data-graph-role="structural-frame" data-composition-frame-kind="%s" data-composition-frame-id="%d" data-composition-frame-label="%s" x="%d" y="%d" width="%d" height="%d" rx="%d" class="%s" stroke-width="1"/>' % (kind, fid, esc(label), x, y, w, h, rx, cls))
        A('')
    A('        <!-- Connection paths (before components for correct z-order) -->')
    for i,(eid, fr, to, label, var, pts, d, _lp) in enumerate(edges):
        cls, sw, marker, _tc = VARIANT[var]
        lab = ' data-edge-label="%s"' % esc(label) if label else ''
        A('        <path data-edge-from="%s" data-edge-to="%s"%s data-edge-key="%d" data-edge-id="%s" data-composition-points="%s" d="%s" class="%s" stroke-width="%s" marker-end="%s"/>' % (fr, to, lab, i, eid, pts, d, cls, sw, marker))
    A('')
    A('        <!-- Components -->')
    for nid, kind, x, y, w, label, sub, tag, ctx in nodes:
        cx = x + w/2.0; cxs = '%g' % cx
        aria = 'Focus %s, %s, %s' % (label, sub, ctx)
        A('        <g id="node-%s" data-node-id="%s" data-node-label="%s" tabindex="0" role="button" aria-label="%s" aria-pressed="false" data-node-kind="%s" data-node-sublabel="%s" data-node-tag="%s" data-node-context="%s">' % (nid, nid, esc(label), esc(aria), kind, esc(sub), esc(tag), esc(ctx)))
        A('          <title>%s · %s · %s · %s</title>' % (esc(label), esc(sub), esc(ctx), esc(tag)))
        A('          <rect x="%d" y="%d" width="%d" height="%d" rx="6" class="c-mask"/>' % (x, y, w, NH))
        A('          <rect x="%d" y="%d" width="%d" height="%d" rx="6" class="c-%s" stroke-width="1.5"/>' % (x, y, w, NH, kind))
        A('          <g aria-hidden="true" data-semantic-sigil="%s" class="semantic-sigil s-%s" transform="translate(%d %d) scale(0.6875)">' % (kind, kind, x+6, y+6))
        A('            ' + SIGILS[kind])
        A('          </g>')
        A('          <text data-node-label="" data-detail-anchor="" x="%s" y="%d" class="t-primary" font-size="11" font-weight="600" text-anchor="middle">%s</text>' % (cxs, y+32, esc(label)))
        A('          <text data-detail="context" x="%s" y="%d" class="t-muted" font-size="9" text-anchor="middle">%s</text>' % (cxs, y+48, esc(sub)))
        A('          <text data-detail="fine" x="%s" y="%d" class="t-%s" font-size="8" text-anchor="middle">%s</text>' % (cxs, y+66, kind, esc(tag)))
        A('        </g>')
        A('')
    A('        <!-- Connection labels -->')
    for i,(eid, fr, to, label, var, pts, d, lp) in enumerate(edges):
        if not label or lp is None: continue
        _c,_s,_m,tc = VARIANT[var]
        lx, ly = lp; w = len(label)*4.9 + 8
        A('        <g data-detail="context" data-edge-from="%s" data-edge-to="%s" data-edge-label="%s" data-edge-key="%d" data-edge-id="%s">' % (fr, to, esc(label), i, eid))
        A('          <rect x="%g" y="%g" width="%g" height="14" rx="3" class="c-mask"/>' % (round(lx - w/2.0, 1), ly-10, round(w,1)))
        A('          <text x="%g" y="%g" class="%s" font-size="8" text-anchor="middle">%s</text>' % (lx, ly, tc, esc(label)))
        A('        </g>')
    A('')
    A('        <!-- Boundary labels (foreground masks keep routes out of titles) -->')
    for kind, fid, label, x, y, w, h, cls, tcls, rx in frames:
        lw = len(label)*5.2 + 8
        A('        <g data-graph-role="structural-frame-label" data-composition-frame-id="%d" data-composition-frame-kind="%s" data-composition-frame-label="%s">' % (fid, kind, esc(label)))
        A('          <rect data-graph-role="structural-frame-label-mask" x="%d" y="%d" width="%g" height="16" rx="3" class="c-mask"/>' % (x+4, y+4, round(lw,1)))
        A('          <text data-boundary-label="" x="%d" y="%d" class="%s" font-size="9" font-weight="600">%s</text>' % (x+8, y+17, tcls, esc(label)))
        A('        </g>')
        A('')
    A('        <!-- Legend -->'); A(''); A('      </svg>')
    return '\n'.join(out)

def cards_html(cards):
    parts=['    <!-- Info Cards -->','    <div class="cards">']
    for dot,title,items in cards:
        parts+=['      <div class="card">','        <div class="card-header">',
                '          <div class="card-dot %s"></div>'%dot,'          <h3>%s</h3>'%esc(title),
                '        </div>','        <ul>']
        parts+=['          <li>&bull; %s</li>'%esc(it) for it in items]
        parts+=['        </ul>','      </div>','']
    parts[-1]='    </div>'
    return '\n'.join(parts)
